### ISSUE TITLE
SyntaxError: await is only valid in async function

### ISSUE THREAD

**Issue by jk171505** [abhinaba-ghosh/any-text#1]
I get this error when run you async/await example. Any advice?

**Comment by abhinaba-ghosh** [comment]
Hi @jk171505 , Many thanks for raising this issue. can you share the code sample, please?

**Comment by jk171505** [comment]
Like I said, this happens when I run your example, copied from the main site:

    var reader = require('any-text');
    const text = await reader.getText(`path-to-file.pdf`);
    console.log(text);

**Comment by abhinaba-ghosh** [comment]
Hi @jk171505 , `await` muset be used inside a `async` function. Like:

```js
var reader = require('any-text');

async getMyText(){
const text = await reader.getText(`path-to-file.pdf`);
console.log(text);
return text;
}
```

Or you can use without await:

```js
var reader = require('any-text');

reader.getText(`path-to-file`).then(function (data) {
  console.log(data);
});
```

**Comment by jk171505** [comment]
Thanks. I Was confused about this example, that it can work just like that.

**Comment by abhinaba-ghosh** [comment]
@jk171505 nice spot! Would you mind raising a PR with a meaningful example? It will help us.
