### ISSUE TITLE
hebrew rtl NOT WORK

### ISSUE THREAD

**Issue by IgalNeeman** [abhinaba-ghosh/any-text#17]
Hello,
its worked, but if i have in the same line hebrew & english like
 אימייל  lalala@gmail.com 

its write for me: comlalala@gmail.com 
its not working good, i'll like and give you star if its work with hebrew also
thank you alot

**Comment by abhinaba-ghosh** [comment]
Hi @IgalNeeman , I am not able to reproduce the issue. I am able to read hebrew text with this library. Can you share a repo for the same?

**Comment by IgalNeeman** [comment]
Hi sorry I'm not using the library anymore

‫בתאריך שבת, 25 בדצמ׳ 2021 ב-19:09 מאת ‪Abhinaba Ghosh‬‏ <‪
***@***.***‬‏>:‬

**Comment by IgalNeeman** [comment]
DONME
