### ISSUE TITLE
Package size mismatch issue

### ISSUE THREAD

**Issue by Prottoy2938** [abhinaba-ghosh/any-text#3]
In [npm](https://www.npmjs.com/package/any-text), it says the package size is around `5 kb`, but I've checked its dependencies and it seems like its actually around `2 MB`.  In [bundlephobia](https://bundlephobia.com/result?p=any-text), it says the same.

Since this is a huge size difference, I would suggest you update the npm package size description.

Also, in the Readme file, it says to install it as a `dev` package, is this package not suitable for production?

**Comment by abhinaba-ghosh** [comment]
H @Prottoy2938, I think bundlephobia is calculating the size based on dependencies of the library. I can't do much in this area. Dependencies can have a long tree of other dependencies. I am curious to know if the size of the library creating a problem in your project?
for the other answer, it can also be included a `dependency`
